function [V,F] = simple_cube()
%SIMPLE_CUBE  construct a triangle mesh for a simple cube
%
% [V,F] = simple_cube();
%
% Outputs:
%  V,F  the triangle mesh of a simple cube

V = [0, 0, 0; ... %dots in MATLAB allow us to insert a linebreak, but continue with the same statement
    1, 0, 0; ...
    0, 1, 0; ...
    1, 1, 0; ...
    0, 0, 1; ...
    1, 0, 1; ...
    0, 1, 1; ...
    1, 1, 1];

F = [1, 2, 3; ...
    2, 4, 3; ...
    1, 2, 5; ...
    2, 6, 5; ...
    2, 4, 8; ...
    2, 8, 6; ...
    4, 3, 7; ...
    4, 7, 8; ...
    3, 1, 7; ...
    1, 5, 7; ...
    5, 6, 7; ...
    6, 8, 7;];

end

